[package]
name = "golang_json_deserialisation"
version = "0.1.0"
authors = ["rfc <reuben.fletchercostin@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"

[[bin]]
name = "golang_json_deserialisation"
path = "main.rs"
